apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-ext-kubeaddons-client
  namespace: kubeaddons-enterprise
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-ext-kubeaddons-client
  namespace: kubeaddons-enterprise
